version: '3'

services:

  django:
    restart: always
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker/django/development/Dockerfile
    command: /start.sh
    env_file: .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
