version: '3.7'

services:
  django:
    restart: always
    container_name: django_server
    build:
      context: .
      dockerfile: ./docker/django/development/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/src
    ports:
      - "8000:8000"
